AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: true

  Include:
    - spec/**/*.rb
    - lib/**/*.rb

  Exclude:
    - vendor/**/*.rb

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - "*.gemspec"

Metrics/MethodLength:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/NumberedParametersLimit:
  Max: 2

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Enabled: false
